// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: read.proto

package minitoolstream_connector

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	StartSequence *uint64                `protobuf:"varint,2,opt,name=start_sequence,json=startSequence,proto3,oneof" json:"start_sequence,omitempty"`
	DurableName   string                 `protobuf:"bytes,3,opt,name=durable_name,json=durableName,proto3" json:"durable_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SubscribeRequest) GetStartSequence() uint64 {
	if x != nil && x.StartSequence != nil {
		return *x.StartSequence
	}
	return 0
}

func (x *SubscribeRequest) GetDurableName() string {
	if x != nil {
		return x.DurableName
	}
	return ""
}

type Notification struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Subject string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	// последний сиквенс доступный для чтения
	Sequence      uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	DurableName   string                 `protobuf:"bytes,2,opt,name=durable_name,json=durableName,proto3" json:"durable_name,omitempty"`
	BatchSize     int32                  `protobuf:"varint,3,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{2}
}

func (x *FetchRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *FetchRequest) GetDurableName() string {
	if x != nil {
		return x.DurableName
	}
	return ""
}

func (x *FetchRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type GetLastSequenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSequenceRequest) Reset() {
	*x = GetLastSequenceRequest{}
	mi := &file_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSequenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSequenceRequest) ProtoMessage() {}

func (x *GetLastSequenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSequenceRequest.ProtoReflect.Descriptor instead.
func (*GetLastSequenceRequest) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{3}
}

func (x *GetLastSequenceRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type GetLastSequenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSequence  uint64                 `protobuf:"varint,1,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastSequenceResponse) Reset() {
	*x = GetLastSequenceResponse{}
	mi := &file_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastSequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastSequenceResponse) ProtoMessage() {}

func (x *GetLastSequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastSequenceResponse.ProtoReflect.Descriptor instead.
func (*GetLastSequenceResponse) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastSequenceResponse) GetLastSequence() uint64 {
	if x != nil {
		return x.LastSequence
	}
	return 0
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_read_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Message) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_read_proto protoreflect.FileDescriptor

const file_read_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"read.proto\x12\x0eminitoolstream\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12*\n" +
	"\x0estart_sequence\x18\x02 \x01(\x04H\x00R\rstartSequence\x88\x01\x01\x12!\n" +
	"\fdurable_name\x18\x03 \x01(\tR\vdurableNameB\x11\n" +
	"\x0f_start_sequence\"D\n" +
	"\fNotification\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\"j\n" +
	"\fFetchRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12!\n" +
	"\fdurable_name\x18\x02 \x01(\tR\vdurableName\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x03 \x01(\x05R\tbatchSize\"2\n" +
	"\x16GetLastSequenceRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\">\n" +
	"\x17GetLastSequenceResponse\x12#\n" +
	"\rlast_sequence\x18\x01 \x01(\x04R\flastSequence\"\x89\x02\n" +
	"\aMessage\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12>\n" +
	"\aheaders\x18\x04 \x03(\v2$.minitoolstream.Message.HeadersEntryR\aheaders\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x84\x02\n" +
	"\rEgressService\x12M\n" +
	"\tSubscribe\x12 .minitoolstream.SubscribeRequest\x1a\x1c.minitoolstream.Notification0\x01\x12@\n" +
	"\x05Fetch\x12\x1c.minitoolstream.FetchRequest\x1a\x17.minitoolstream.Message0\x01\x12b\n" +
	"\x0fGetLastSequence\x12&.minitoolstream.GetLastSequenceRequest\x1a'.minitoolstream.GetLastSequenceResponseBMZKgithub.com/moroshma/MiniToolStreamConnector/model;minitoolstream_connectorb\x06proto3"

var (
	file_read_proto_rawDescOnce sync.Once
	file_read_proto_rawDescData []byte
)

func file_read_proto_rawDescGZIP() []byte {
	file_read_proto_rawDescOnce.Do(func() {
		file_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_read_proto_rawDesc), len(file_read_proto_rawDesc)))
	})
	return file_read_proto_rawDescData
}

var file_read_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_read_proto_goTypes = []any{
	(*SubscribeRequest)(nil),        // 0: minitoolstream.SubscribeRequest
	(*Notification)(nil),            // 1: minitoolstream.Notification
	(*FetchRequest)(nil),            // 2: minitoolstream.FetchRequest
	(*GetLastSequenceRequest)(nil),  // 3: minitoolstream.GetLastSequenceRequest
	(*GetLastSequenceResponse)(nil), // 4: minitoolstream.GetLastSequenceResponse
	(*Message)(nil),                 // 5: minitoolstream.Message
	nil,                             // 6: minitoolstream.Message.HeadersEntry
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_read_proto_depIdxs = []int32{
	6, // 0: minitoolstream.Message.headers:type_name -> minitoolstream.Message.HeadersEntry
	7, // 1: minitoolstream.Message.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: minitoolstream.EgressService.Subscribe:input_type -> minitoolstream.SubscribeRequest
	2, // 3: minitoolstream.EgressService.Fetch:input_type -> minitoolstream.FetchRequest
	3, // 4: minitoolstream.EgressService.GetLastSequence:input_type -> minitoolstream.GetLastSequenceRequest
	1, // 5: minitoolstream.EgressService.Subscribe:output_type -> minitoolstream.Notification
	5, // 6: minitoolstream.EgressService.Fetch:output_type -> minitoolstream.Message
	4, // 7: minitoolstream.EgressService.GetLastSequence:output_type -> minitoolstream.GetLastSequenceResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_read_proto_init() }
func file_read_proto_init() {
	if File_read_proto != nil {
		return
	}
	file_read_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_read_proto_rawDesc), len(file_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_read_proto_goTypes,
		DependencyIndexes: file_read_proto_depIdxs,
		MessageInfos:      file_read_proto_msgTypes,
	}.Build()
	File_read_proto = out.File
	file_read_proto_goTypes = nil
	file_read_proto_depIdxs = nil
}
