// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: model/read.proto

package minitoolstream_connector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EgressService_Subscribe_FullMethodName       = "/minitoolstream.EgressService/Subscribe"
	EgressService_Fetch_FullMethodName           = "/minitoolstream.EgressService/Fetch"
	EgressService_GetLastSequence_FullMethodName = "/minitoolstream.EgressService/GetLastSequence"
)

// EgressServiceClient is the client API for EgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Сервис для выдачи (чтения) сообщений
type EgressServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error)
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error)
	GetLastSequence(ctx context.Context, in *GetLastSequenceRequest, opts ...grpc.CallOption) (*GetLastSequenceResponse, error)
}

type egressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEgressServiceClient(cc grpc.ClientConnInterface) EgressServiceClient {
	return &egressServiceClient{cc}
}

func (c *egressServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Notification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EgressService_ServiceDesc.Streams[0], EgressService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Notification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressService_SubscribeClient = grpc.ServerStreamingClient[Notification]

func (c *egressServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EgressService_ServiceDesc.Streams[1], EgressService_Fetch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchRequest, Message]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressService_FetchClient = grpc.ServerStreamingClient[Message]

func (c *egressServiceClient) GetLastSequence(ctx context.Context, in *GetLastSequenceRequest, opts ...grpc.CallOption) (*GetLastSequenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastSequenceResponse)
	err := c.cc.Invoke(ctx, EgressService_GetLastSequence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EgressServiceServer is the server API for EgressService service.
// All implementations must embed UnimplementedEgressServiceServer
// for forward compatibility.
//
// Сервис для выдачи (чтения) сообщений
type EgressServiceServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error
	Fetch(*FetchRequest, grpc.ServerStreamingServer[Message]) error
	GetLastSequence(context.Context, *GetLastSequenceRequest) (*GetLastSequenceResponse, error)
	mustEmbedUnimplementedEgressServiceServer()
}

// UnimplementedEgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEgressServiceServer struct{}

func (UnimplementedEgressServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Notification]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedEgressServiceServer) Fetch(*FetchRequest, grpc.ServerStreamingServer[Message]) error {
	return status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedEgressServiceServer) GetLastSequence(context.Context, *GetLastSequenceRequest) (*GetLastSequenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLastSequence not implemented")
}
func (UnimplementedEgressServiceServer) mustEmbedUnimplementedEgressServiceServer() {}
func (UnimplementedEgressServiceServer) testEmbeddedByValue()                       {}

// UnsafeEgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EgressServiceServer will
// result in compilation errors.
type UnsafeEgressServiceServer interface {
	mustEmbedUnimplementedEgressServiceServer()
}

func RegisterEgressServiceServer(s grpc.ServiceRegistrar, srv EgressServiceServer) {
	// If the following call pancis, it indicates UnimplementedEgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EgressService_ServiceDesc, srv)
}

func _EgressService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EgressServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Notification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressService_SubscribeServer = grpc.ServerStreamingServer[Notification]

func _EgressService_Fetch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EgressServiceServer).Fetch(m, &grpc.GenericServerStream[FetchRequest, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EgressService_FetchServer = grpc.ServerStreamingServer[Message]

func _EgressService_GetLastSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServiceServer).GetLastSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EgressService_GetLastSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServiceServer).GetLastSequence(ctx, req.(*GetLastSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EgressService_ServiceDesc is the grpc.ServiceDesc for EgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minitoolstream.EgressService",
	HandlerType: (*EgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLastSequence",
			Handler:    _EgressService_GetLastSequence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _EgressService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Fetch",
			Handler:       _EgressService_Fetch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "model/read.proto",
}
